# 13 - COMANDO ALTER

-- https://dev.mysql.com/doc/refman/8.0/en/alter-table.html
ALTER DATABASE tads DEFAULT COLLATE='utf8_general_ci';

ALTER TABLE TESTE MODIFY COLUMN nome VARCHAR(5) NOT NULL;

ALTER TABLE TESTE ADD COLUMN descricao TEXT AFTER nome;

ALTER TABLE TESTE ADD COLUMN titulo TEXT FIRST;

ALTER TABLE TESTE DROP COLUMN titulo;

# EXECUTA MAIS RAPIDO
# RESETA O AUTO INCREMENTE
# NÃO POSSUI WHERE
TRUNCATE TABLE TESTE;

# TEM QUE USAR COM O COMANDO WHERE
DELETE FROM TESTE;

RENAME TABLE TESTE TO OUTRO_NOME;

DROP TABLE IF EXISTS OUTRO_NOME;

DROP DATABASE IF EXISTS tads;
